# reusable workflow
name: .build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

env:
  # FIXME: use dockereng/packaging-cache
  BUILD_CACHE_REGISTRY_SLUG: crazymax/docker-packaging-cache

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        pkg:
          - debian10
          - debian11
          - ubuntu1804
          - ubuntu2004
          - ubuntu2204
          - centos7
          - centos9
          - fedora37
          - static
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Prepare
        run: |
          # Push cache to regitry only on main (secrets not available from fork)
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "BUILD_CACHE_REGISTRY_PUSH=1" >> $GITHUB_ENV
          fi
          # Limit to local platform for pkgs other than static for performance
          # reasons. See common/vars.mk and common/build.mk for more info on
          # filtered platforms
          if [ "${{ matrix.pkg }}" != "static" ]; then
            echo "LOCAL_PLATFORM=1" >> $GITHUB_ENV
          fi
      -
        name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        run: |
          make -C pkg/${{ inputs.name }} build-${{ matrix.pkg }}
      -
        name: List artifacts
        run: |
          tree -nh ./pkg/${{ inputs.name }}/bin
