# reusable workflow
name: .build

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      envs:
        required: false
        type: string

env:
  BUILD_CACHE_REGISTRY_SLUG: dockereng/packaging-cache
  GHA_DEFAULT_MATRIX: minimal

jobs:
  prepare:
    runs-on: ubuntu-24.04
    outputs:
      includes: ${{ steps.matrix.outputs.includes }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Matrix
        id: matrix
        uses: actions/github-script@v7
        env:
          INPUT_NAME: ${{ inputs.name }}
        with:
          script: |
            const inpName = core.getInput('name');
            
            let def = {};
            await core.group(`Parsing definition`, async () => {
              const resPrint = await exec.getExecOutput('docker', ['buildx', 'bake', 'pkg', '--print'], {
                ignoreReturnCode: true
              });
              if (resPrint.stderr.length > 0 && resPrint.exitCode != 0) {
                throw new Error(res.stderr);
              }
              def = JSON.parse(resPrint.stdout.trim());
            });
            
            await core.group(`Generating matrix`, async () => {
              const includes = [];
              for (const targetName of Object.keys(def.target)) {
                if (!targetName.startsWith(`pkg-${inpName}`)) {
                  continue;
                }
                const match = targetName.match(/^pkg-(.+)-([^-]+)$/);
                if (!match) {
                  throw new Error(`Invalid target name: ${targetName}`);
                }
                const pkgName = match[1];
                const distro = match[2];
                const target = def.target[targetName];
                if (target.platforms && target.platforms.length > 0) {
                  target.platforms.forEach(platform => {
                    includes.push({
                      runner: platform.startsWith('linux/arm') ? 'ubuntu-24.04-arm' : 'ubuntu-24.04',
                      distro: distro,
                      platform: platform
                    });
                  });
                } else {
                  includes.push({
                    runner: 'ubuntu-24.04',
                    distro: distro
                  });
                }
              }
              core.info(JSON.stringify(includes, null, 2));
              core.setOutput('includes', JSON.stringify(includes));
            });

  build:
    runs-on: ${{ matrix.runner }}
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.includes) }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Environment variables
        run: |
          for l in "${{ inputs.envs }}"; do
            echo "${l?}" >> $GITHUB_ENV
          done
      -
        name: Prepare
        run: |
          # Set platform pair for artifact upload
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
          # Push cache to regitry only on main (secrets not available from fork)
          # and not on workflow_dispatch event
          if [ "${{ github.ref }}" = "refs/heads/main" ] && [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
            echo "BUILD_CACHE_REGISTRY_PUSH=1" >> $GITHUB_ENV
          fi
          # Limit to local platform for pkgs other than static for performance
          # reasons. See docker-bake.hcl for more info on filtered platforms.
          if [ "${{ matrix.distro }}" != "static" ]; then
            echo "LOCAL_PLATFORM=1" >> $GITHUB_ENV
          fi
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
      -
        name: Build
        uses: docker/bake-action@v6
        with:
          source: .
          targets: pkg-${{ inputs.name }}-${{ matrix.distro }}
          set: |
            *.platform=${{ matrix.platform }}
      -
        name: List artifacts
        run: |
          tree -nh ./bin/pkg/${{ inputs.name }}
#      -
#        name: Verify
#        run: |
#          make -C pkg/${{ inputs.name }} run-verify-${{ matrix.pkg }}
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-pkg-${{ inputs.name }}-${{ matrix.distro }}-${{ env.PLATFORM_PAIR }}
          path: ./bin/pkg/${{ inputs.name }}/*
          if-no-files-found: error
          retention-days: 1

  dummy-release:
    runs-on: ubuntu-24.04
    needs:
      - build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Environment variables
        run: |
          for l in "${{ inputs.envs }}"; do
            echo "${l?}" >> $GITHUB_ENV
          done
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
      -
        name: Download binaries
        uses: actions/download-artifact@v4
        with:
          path: ./bin/pkg/${{ inputs.name }}
          pattern: build-pkg-*
          merge-multiple: true
      -
        name: List binaries
        run: |
          tree -nh ./bin/pkg/${{ inputs.name }}
#      -
#        name: Generate metadata
#        run: |
#          make -C pkg/${{ inputs.name }} metadata
#      -
#        name: Summary
#        run: |
#          for l in $(cat ./pkg/${{ inputs.name }}/bin/metadata.env); do
#            export "${l?}"
#          done
#
#          cat >> "$GITHUB_STEP_SUMMARY" <<-EOF
#          * repo: ${REPO}
#          * ref: \`${REF}\`
#          * version: \`${VERSION}\`
#          * commit: [\`${COMMIT}\`](${REPO}/commit/${COMMIT})
#          EOF
#
#          if [ "${{ inputs.name }}" = "containerd" ]; then
#            cat >> "$GITHUB_STEP_SUMMARY" <<-EOF
#          * runc
#            * repo: ${RUNC_REPO}
#            * ref: \`${RUNC_REF}\`
#            * version: \`${RUNC_VERSION}\`
#            * commit: [\`${RUNC_COMMIT}\`](${RUNC_REPO}/commit/${RUNC_COMMIT})
#          EOF
#          fi
#
#          cat >> "$GITHUB_STEP_SUMMARY" <<-EOF
#          * packages: \`$(find ./pkg/${{ inputs.name }}/bin -type f | wc -l)\` files
#          * size: \`$(du -sh ./pkg/${{ inputs.name }}/bin | awk '{print $1}')\`
#          EOF
#      -
#        name: Release
#        uses: docker/bake-action@v6
#        with:
#          workdir: ./pkg/${{ inputs.name }}
#          source: .
#          targets: release
#          provenance: false
#          set: |
#            *.output=/tmp/release
#      -
#        name: List release artifacts
#        run: |
#          tree /tmp/release
