name: build-buildx

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
      - 'buildx/[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/.build.yml'
      - '.github/workflows/build-buildx.yml'
      - 'hack/scripts/**'
      - 'pkg/buildx/**'
  pull_request:
    branches:
      - 'main'
      - 'buildx/[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/.build.yml'
      - '.github/workflows/build-buildx.yml'
      - 'hack/scripts/**'
      - 'pkg/buildx/**'

jobs:
  run:
    uses: ./.github/workflows/.build.yml
    with:
      name: buildx
    secrets: inherit
