name: build-sbom

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
      - 'sbom/[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/.build.yml'
      - '.github/workflows/build-sbom.yml'
      - 'hack/scripts/**'
      - 'pkg/sbom/**'
  pull_request:
    branches:
      - 'main'
      - 'sbom/[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/.build.yml'
      - '.github/workflows/build-sbom.yml'
      - 'hack/scripts/**'
      - 'pkg/sbom/**'

jobs:
  run:
    uses: ./.github/workflows/.build.yml
    with:
      name: sbom
    secrets: inherit
