name: build

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Run
        uses: docker/bake-action@v2
        with:
          targets: validate

  build:
    runs-on: ubuntu-20.04
    needs:
      - validate
    strategy:
      fail-fast: false
      matrix:
        type:
          - apk
          - deb
          - rpm
          - static
        pkg:
          - buildx
          - compose
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        run: |
          make ${{ matrix.type }}-${{ matrix.pkg }}
      -
        name: Upload pkgs
        uses: actions/upload-artifact@v3
        with:
          name: pkgs
          path: ./bin/*
          if-no-files-found: error

  release:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Download pkgs
        uses: actions/download-artifact@v3
        with:
          name: pkgs
          path: ./bin
      -
        name: List pkgs
        run: |
          tree -nh ./bin
