name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Run
        uses: docker/bake-action@v2
        with:
          targets: validate

  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        name:
          - docker-engine
          - docker-cli
          - containerd
          - buildx
          - compose
          - scan
          - credential-helpers
        pkg:
          - deb
          - rpm
          - static
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        # necessary to use gha cache export
        name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v2
      -
        name: Build
        run: |
          make -j$(nproc) -C pkg/${{ matrix.name }} all-${{ matrix.pkg }}
        env:
          BUILD_CACHE_SCOPE: build-${{ matrix.name }}-${{ matrix.pkg }}
      -
        name: List artifacts
        run: |
          tree -nh ./pkg/${{ matrix.name }}/bin
# FIXME: Uncomment when repo made public
#      -
#        name: Upload artifacts
#        uses: actions/upload-artifact@v3
#        with:
#          name: ${{ matrix.name }}
#          path: ./pkg/${{ matrix.name }}/bin/*
#          if-no-files-found: error
#          retention-days: 1

#  dummy-release:
#    runs-on: ubuntu-20.04
#    needs:
#      - build
#    strategy:
#      fail-fast: false
#      matrix:
#        name:
#          - docker-cli
#          - buildx
#          - compose
#          - credential-helpers
#    steps:
#      -
#        name: Checkout
#        uses: actions/checkout@v3
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      -
#        name: Download binaries
#        uses: actions/download-artifact@v3
#        with:
#          name: ${{ matrix.name }}
#          path: ./pkg/${{ matrix.name }}/bin
#      -
#        name: Release
#        uses: docker/bake-action@v2
#        with:
#          workdir: ./pkg/${{ matrix.name }}
#          targets: release
#          set: |
#            *.output=/tmp/release
#      -
#        name: List release artifacts
#        run: |
#          tree /tmp/release
