name: build-docker-cli

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
      - 'docker/[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/.build.yml'
      - '.github/workflows/build-docker-cli.yml'
      - 'hack/scripts/**'
      - 'pkg/docker-cli/**'
      - 'docker-bake.hcl'
  pull_request:
    branches:
      - 'main'
      - 'docker/[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/.build.yml'
      - '.github/workflows/build-docker-cli.yml'
      - 'hack/scripts/**'
      - 'pkg/docker-cli/**'
      - 'docker-bake.hcl'

jobs:
  run:
    uses: ./.github/workflows/.build.yml
    with:
      name: docker-cli
    secrets: inherit
