name: build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Run
        uses: docker/bake-action@v2
        with:
          targets: validate

  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        pkg:
          - buildx
          - compose
          - credential-helpers
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        run: |
          make -j$(nproc) -C pkg/${{ matrix.pkg }} all
      -
        name: List artifacts
        run: |
          tree -nh ./pkg/${{ matrix.pkg }}/bin
      -
        name: Dummy release
        uses: docker/bake-action@v2
        with:
          workdir: ./pkg/${{ matrix.pkg }}
          targets: release
          set: |
            *.output=/tmp/release
      -
        name: List release artifacts
        run: |
          tree /tmp/release
