name: build-compose

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
      - 'compose/[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/.build.yml'
      - '.github/workflows/build-compose.yml'
      - 'hack/scripts/**'
      - 'pkg/compose/**'
  pull_request:
    branches:
      - 'main'
      - 'compose/[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/.build.yml'
      - '.github/workflows/build-compose.yml'
      - 'hack/scripts/**'
      - 'pkg/compose/**'

jobs:
  run:
    uses: ./.github/workflows/.build.yml
    with:
      name: compose
    secrets: inherit
