name: build-buildkit

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      pkgs:
        description: 'Packages to build (minimal, all or space separated list)'
        default: 'minimal'
        required: false
        type: string
  push:
    branches:
      - 'main'
      - 'buildkit/[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/.build.yml'
      - '.github/workflows/build-buildkit.yml'
      - 'common/**'
      - 'pkg/buildkit/**'
  pull_request:
    paths:
      - '.github/workflows/.build.yml'
      - '.github/workflows/build-buildkit.yml'
      - 'common/**'
      - 'pkg/buildkit/**'

jobs:
  run:
    uses: ./.github/workflows/.build.yml
    with:
      name: buildkit
    secrets: inherit
