name: build-containerd

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      pkgs:
        description: 'Packages to build (minimal, all or space separated list)'
        default: 'minimal'
        required: false
        type: string
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - '.github/workflows/.build.yml'
      - '.github/workflows/build-containerd.yml'
      - 'common/**'
      - 'pkg/containerd/**'

jobs:
  run:
    uses: ./.github/workflows/.build.yml
    with:
      name: containerd
    secrets: inherit
