name: build-compose

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - '.github/workflows/.build-remote.yml'
      - '.github/workflows/build-compose.yml'
      - 'common/**'
      - 'pkg/compose/**'

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        pkg:
          - deb
          - rpm
          - static
    uses: ./.github/workflows/.build-remote.yml
    with:
      name: compose
      pkg: ${{ matrix.pkg }}
    secrets: inherit
