name: build

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Run
        uses: docker/bake-action@v2
        with:
          targets: validate

  build:
    runs-on: ubuntu-latest
    needs:
      - validate
    strategy:
      fail-fast: false
      matrix:
        type:
          - apk
          - deb
          - rpm
          - static
        pkg:
          - buildx
          - compose
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        run: |
          make ${{ matrix.type }}-${{ matrix.pkg }}
