name: build-docker-engine

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'main'
      - 'docker/[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/.build.yml'
      - '.github/workflows/build-docker-engine.yml'
      - 'hack/scripts/**'
      - 'pkg/docker-engine/**'
  pull_request:
    branches:
      - 'main'
      - 'docker/[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/.build.yml'
      - '.github/workflows/build-docker-engine.yml'
      - 'hack/scripts/**'
      - 'pkg/docker-engine/**'

jobs:
  run:
    uses: ./.github/workflows/.build.yml
    with:
      name: docker-engine
    secrets: inherit
