name: build-docker-cli

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - '.github/workflows/.build.yml'
      - '.github/workflows/build-docker-cli.yml'
      - 'common/**'
      - 'pkg/docker-cli/**'

jobs:
  run:
    uses: ./.github/workflows/.build.yml
    with:
      name: docker-cli
    secrets: inherit
