# This workflow runs nighly builds for each package.
name: nightly

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 0'

env:
  DISABLED_PACKAGES: scan,sbom

jobs:
  prepare:
    runs-on: ubuntu-24.04
    outputs:
      matrix: ${{ steps.pkgs.outputs.matrix }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Create matrix
        id: pkgs
        run: |
          pkgs=$(find ./pkg -maxdepth 1 -type d -printf '%P ')
          pkgs=$(echo $pkgs | jq -cR --arg exclude "${{ env.DISABLED_PACKAGES }}" 'split(" ") | map(select(. | IN($exclude | split(",")) | not))')
          echo "matrix=$pkgs" >> ${GITHUB_OUTPUT}
      -
        name: Show matrix
        run: |
          echo ${{ steps.pkgs.outputs.matrix }}

  build:
    uses: ./.github/workflows/.build.yml
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        pkg: ${{ fromJson(needs.prepare.outputs.matrix) }}
    with:
      name: ${{ matrix.pkg }}
      push: true
      envs: |
        NIGHTLY_BUILD=1
    secrets: inherit
