name: release-containerd

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 3 * * 0' # every sunday at 3am
  workflow_dispatch:
    inputs:
      repo:
        description: 'Override repo'
        required: false
        type: string
      ref:
        description: 'Override ref'
        required: false
        type: string
      runc_repo:
        description: 'Override runc repo'
        required: false
        type: string
      runc_ref:
        description: 'Override runc ref'
        required: false
        type: string
      release:
        description: 'Push image and create release'
        required: false
        type: boolean

jobs:
  manual:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/.release.yml
    with:
      name: containerd
      release: ${{ inputs.release }}
      env: |
        CONTAINERD_REPO=${{ inputs.repo }}
        CONTAINERD_REF=${{ inputs.ref }}
        RUNC_REPO=${{ inputs.runc_repo }}
        RUNC_REF=${{ inputs.runc_ref }}
    secrets: inherit

  schedule:
    if: github.event_name == 'schedule'
    uses: ./.github/workflows/.release.yml
    with:
      name: containerd
      env: |
        NIGHTLY_BUILD=1
        CONTAINERD_REF=main
    secrets: inherit
