name: release-docker-cli

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 5 * * 0' # every sunday at 5am
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref (e.g. v23.0.0)'
        required: true
        type: string
      repo:
        description: 'Override default repo'
        required: false
        type: string
      release:
        description: 'Push image and create release'
        required: false
        type: boolean

jobs:
  manual:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/.release.yml
    with:
      name: docker-cli
      release: ${{ inputs.release }}
      env: |
        DOCKER_CLI_REPO=${{ inputs.repo }}
        DOCKER_CLI_REF=${{ inputs.ref }}
    secrets: inherit

  schedule:
    if: github.event_name == 'schedule'
    uses: ./.github/workflows/.release.yml
    with:
      name: docker-cli
      env: |
        NIGHTLY_BUILD=1
    secrets: inherit
