name: release

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package (e.g. buildx)'
        required: true
        type: string
      release:
        description: 'Push image and create release'
        required: false
        type: boolean

env:
  # FIXME: temporary for testing, use dockereng/packaging
  REPO_SLUG: crazymax/docker-packaging

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Prepare
        run: |
          version=$(make ${{ inputs.package }}-version)
          git_tag="${{ inputs.package }}/$version"
          echo "Package: ${{ inputs.package }}"
          echo "Release: ${{ inputs.release }}"
          echo "Git tag prefix: $git_tag"
          echo "GIT_TAG=$git_tag" >> $GITHUB_ENV
      -
        name: Build pkgs
        run: |
          make -j 4 -C pkg/${{ inputs.package }} pkg
          tree -nh ./pkg/${{ inputs.package }}/bin
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REPO_SLUG }}
          tags: |
            type=ref,event=pr
            type=raw,value=${{ env.GIT_TAG }}
            type=raw,value=${{ env.GIT_TAG }}-${{ github.run_number }}
            type=raw,value=${{ env.GIT_TAG }}-{{sha}}
          labels: |
            com.github.docker.packaging.run_id=${{ github.run_id }}
            com.github.docker.packaging.run_number=${{ github.run_number }}
          bake-target: meta-helper
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        if: ${{ inputs.release }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build image
        uses: docker/bake-action@v2
        with:
          workdir: ./pkg/${{ inputs.package }}
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: pkg-cross
          set: |
            *.output=type=image,push=${{ inputs.release }}
      -
        name: Create release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        if: ${{ inputs.release }}
        with:
          name: ${{ env.GIT_TAG }}-${{ github.run_number }}
          tag_name: ${{ env.GIT_TAG }}-${{ github.run_number }}
          target_commitish: ${{ github.sha }}
          body: |
            Image available at [https://hub.docker.com/r/${{ env.REPO_SLUG }}](https://hub.docker.com/r/${{ env.REPO_SLUG }})
            ```json
            ${{ steps.meta.outputs.json }}
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
