name: release-scan

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Override repo'
        required: false
        type: string
      ref:
        description: 'Override ref'
        required: false
        type: string
      release:
        description: 'Push image and create release'
        required: false
        type: boolean

jobs:
  manual:
    uses: ./.github/workflows/.release.yml
    with:
      name: scan
      release: ${{ inputs.release }}
      env: |
        SCAN_REPO=${{ inputs.repo }}
        SCAN_REF=${{ inputs.ref }}
    secrets: inherit
